name: GitHub Snake
on:
  schedule:
    - cron: '0 0 * * *'  # runs daily (fixed the missing *)
  push:
    branches:
      - main
  workflow_dispatch:  # allows manual triggering
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # required for committing the output
    steps:
      - uses: actions/checkout@v4
      - name: Generate GitHub Contribution Snake
        uses: platane/snk@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          outputs: |
            output/github-snake.svg
            output/github-snake-dark.svg?palette=github-dark&background_color=0d1117
            output/github-snake.gif?color_snake=#58a6ff&color_dots=#161b22,#0e4429,#006d32,#26a641,#39d353
      - name: Push to main branch
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add output/
          git commit -m "Update snake animation" || exit 0
          git push
